name: Wokwi CI - Estacionamento Inteligente

on:
  push:
    branches: [ main, feat/actions-build ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-simulate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build filesystem with main.py
        run: |
          docker build -t esp32-python-fs -f Dockerfile .
          docker run --name esp32-python-fs-builder esp32-python-fs /bin/bash
          docker cp esp32-python-fs-builder:/fs.bin .

      - name: Run Wokwi simulation
        uses: wokwi/wokwi-ci-action@v1
        with:
          token: ${{ secrets.WOKWI_API_KEY }}
          path: .
          diagram_file: diagram.json
          expect_text: ESTACIONAMENTO
          timeout: 10000
