name: Wokwi MicroPython CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalar ferramentas
        run: |
          pip install mpremote
          wget -q -O wokwi-cli https://github.com/wokwi/wokwi-cli/releases/latest/download/wokwi-cli-linuxstatic-x64
          chmod +x wokwi-cli

      - name: Baixar firmware MicroPython ESP32
        run: |
          wget -q -O micropython.bin https://github.com/wokwi/wokwi-vscode-micropython/raw/main/esp32/firmware.bin

      - name: Rodar Wokwi
        env:
          WOKWI_CLI_TOKEN: ${{ secrets.WOKWI_CLI_TOKEN }}
        run: |
          ./wokwi-cli --timeout 30000 --diagram-file diagram.json . > serial.log 2>&1 &
          sleep 5
          python -m mpremote connect port:rfc2217://localhost:4000 run main.py | tee -a serial.log
          grep "ESTACIONAMENTO" serial.log